name: remuneracao_media_docentes
profile: remuneracao_media_docentes
version: 1.0.0

model-paths:
  - models

models:
  remuneracao_media_docentes:
    silver:
      +materialized: external
      +format: parquet
    gold:
      +materialized: external
      +format: parquet

flags:
  require_generic_test_arguments_property: true
